manager_ha_homepage:
    pattern:  /
    defaults: { _controller: ManagerHABundle:Default:index }
    
manager_ha_log:
    pattern:  /log
    defaults: { _controller: ManagerHABundle:Default:log }

manager_ha_sync:
    pattern:  /sync/ip/{ip}
    defaults: { _controller: ManagerHABundle:Default:sync }

manager_ha_restart_mha:
    pattern:  /restart_mha
    defaults: { _controller: ManagerHABundle:Default:restart_mha }

manager_ha_start_mha:
    pattern:  /start_mha
    defaults: { _controller: ManagerHABundle:Default:start_mha }

manager_ha_stop_mha:
    pattern:  /stop_mha
    defaults: { _controller: ManagerHABundle:Default:stop_mha }


manager_ha_change_public_ip:
    pattern:  /change_public_ip/ip/{ip}
    defaults: { _controller: ManagerHABundle:Default:change_public_ip }

manager_ha_remove_public_ip:
    pattern:  /remove_public_ip/ip/{ip}
    defaults: { _controller: ManagerHABundle:Default:remove_public_ip }