manager_ha_homepage:
    pattern:  /
    defaults: { _controller: ManagerHABundle:Default:index }
    
manager_ha_log:
    pattern:  /log
    defaults: { _controller: ManagerHABundle:Default:log }

manager_ha_sync:
    pattern:  /sync/ip/{ip}
    defaults: { _controller: ManagerHABundle:Default:sync }

manager_ha_start_mha:
    pattern:  /start_mha
    defaults: { _controller: ManagerHABundle:Default:start_mha }
