parameters:
#    manager_ha.example.class: Manager\HABundle\Example

services:
#    manager_ha.example:
#        class: %manager_ha.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
