#!/bin/bash

#########################################################################################################
##############################             CHECK SYNCHRONIZE          ###################################
#########################################################################################################


########################################### PARAMETERS ##################################################

. HA.conf
. $(dirname $0)/HA.conf
. $(dirname $0)/functions

synchronize=false

####################################### END OF PARAMETERS ###############################################


############################################# PROGRAM ###################################################

config_parser $mha_conf;
config.section.server1;
flag=error.flag
flagpath=$script_path$flag

for (( i = 0; i < ${#ip_bdd[@]}; i++ )); do
    if [ ${ip_bdd[$i]} != $hostname ]; then
        Slave_IO_Running=`mysql -h ${ip_bdd[$i]} -u $db_user -p$db_password $db_name -e 'SHOW SLAVE STATUS\G' | grep 'Slave_IO_Running' | awk -F': ' {'print $2'}`
        Slave_SQL_Running=`mysql -h ${ip_bdd[$i]} -u $db_user -p$db_password $db_name -e 'SHOW SLAVE STATUS\G' | grep 'Slave_SQL_Running'| awk -F': ' {'print $2'}`
        if [ -n "$Slave_IO_Running" ] && [ -n "$Slave_SQL_Running" ]; then
            if [ $Slave_IO_Running = No ] || [ $Slave_SQL_Running = No ]; then
                pbSync
            else
                sync
            fi
        else
                pbSync bdd
        fi
    fi
done

if [ $synchronize = true ]; then
        /bin/bash $script_path"synchronize --master=$hostname --change_mha_conf=false"
fi

########################################### END PROGRAM #################################################