#!/bin/bash

###################################### PARAMETERS ##############################################

. HA.conf
. $(dirname $0)/HA.conf

synchronize=false

printer='script_perso'

config_parser () {
	local iniFile="$1";
    local tmpFile=$( mktemp /tmp/`basename $iniFile`.XXXXXX );
    local intLines;
    local binSED=$( which sed );
    cp $iniFile $tmpFile;

    $binSED -i -e 's/[ \t]*=[ \t]*/=/g' $tmpFile;
    $binSED -i -e 's/\[\([A-Za-z0-9[:space:]]*\)\]/config.section.\1() \{/g' $tmpFile;
    $binSED -i -e 's/ //g' $tmpFile;
    $binSED -i -e 's/config\.section\./\}\'$'\nconfig\.section\./g' $tmpFile;

    # remove first line
    intLines=$( wc -l $tmpFile | awk '{ print $1}' );
    let "intLines=$intLines - 1";
    tail -n $intLines $tmpFile > $tmpFile-2;
    mv -f $tmpFile-2 $tmpFile;

    # add the last brace
    echo -e "\n}" >> $tmpFile;

    source $tmpFile;
    rm -f $tmpFile;
}

pbSync () {
    bdd="$1";
	touch $flagpath
	
	if [ $bdd == 'bdd' ]; then 
		echo probleme de base de donnees
		if [ -f $flagpath ]; then
    		echo j'envoi un mail car la bdd est down
        	#echo "MYSQL : Le serveur MYSQL ne fonctionne plus sur $ip !!! at `eval date +%d/%m/%Y":"%H:%M`" | mail -s "Le serveur MYSQL ne fonctionne plus sur $ip !!! at `eval date +%d/%m/%Y":"%H:%M`" "maintenance@auguria.net"
		fi
	else
		echo probleme de synchronisation
		if [ -f $flagpath ]; then
    		echo j'envoi un mail car il n'y a plus de synchronisation
        	#echo "MYSQL : Le serveur $ip n'est plus synchrone !!! at `eval date +%d/%m/%Y":"%H:%M`" | mail -s "MYSQL : Le serveur $ip n'est plus synchrone !!! at `eval date +%d/%m/%Y":"%H:%M`" "maintenance@auguria.net"
		fi
	fi
}

sync () {
	echo Aucun probleme de synchronisation
	if [ -f $flagpath ]; then
    	rm $flagpath
	fi
}

############################################### PROGRAMME ################################"

config_parser $mha_conf;
config.section.server1;
ip=$hostname;
flag=error.flag
flagpath=$script_path$flag
echo -e "\033[32m $printer[info] Connexion en ssh a $ip_magento \033[0m"
echo -e "\033[32m $printer[info] lecture de l'adresse ip dans le fichier mha.conf \033[0m"

for (( i = 0; i < ${#ip_bdd[@]}; i++ )); do
    if [ ${ip_bdd[$i]} != $ip ]; then
        Slave_IO_Running=`mysql -h ${ip_bdd[$i]} -u $db_user -p$db_password $db_name -e 'SHOW SLAVE STATUS\G' | grep 'Slave_IO_Running' | awk -F': ' {'print $2'}`
        Slave_SQL_Running=`mysql -h ${ip_bdd[$i]} -u $db_user -p$db_password $db_name -e 'SHOW SLAVE STATUS\G' | grep 'Slave_SQL_Running'| awk -F': ' {'print $2'}`
        if [ -n "$Slave_IO_Running" ] && [ -n "$Slave_SQL_Running" ]; then
            if [ $Slave_IO_Running = No ] || [ $Slave_SQL_Running = No ]; then
                pbSync
            else
                sync
            fi
        else
                pbSync bdd
        fi
    fi
done

if [ $synchronize = true ]; then
        /bin/bash $script_path"synchronize --master=$ip --change_mha_conf=false"
fi
