#!/bin/bash

for i in $*; do 
	tmp=$(echo $i | cut -d = -f2)
	[[ $i == --ip=* ]] && ip=$tmp
	[[ $i == --user=* ]] && user=$tmp
	[[ $i == --path=* ]] && path=$tmp
	tmp=''
done

if [[ ! -z "$ip" ]] &&  [[ ! -z "$user" ]] && [[ ! -z "$path" ]]; 
then 
	sudo ssh $user@$ip cat $path
fi
